# core/ai_orchestrator.py
import time
import concurrent.futures
from typing import List, Dict, Any
from core.orchestrator import Orchestrator, AttackPhase
from core.ai_assistant import AIAssistant
from core.log_config import get_logger

logger = get_logger("ai_orchestrator")

class AIOrchestrator(Orchestrator):
    def __init__(self, target: str, ip: str):
        super().__init__(target, ip)
        self.ai = AIAssistant()
        # Dynamic queue for tasks generated by the planner
        self.dynamic_tasks = []   # list of task dicts (same structure as self.tasks)
        logger.info("AI Orchestrator initialized (7s rate limiting + dynamic planning)")

    def _run_task(self, task):
        agent = task["agent"]
        name = task["name"]
        phase = task["phase"]

        # Pre-task AI analysis
        logger.info(f"Requesting pre-analysis for {name}")
        pre_analysis = self.ai.analyze_before_task(
            agent_name=name,
            phase=phase.name,
            state=self.state,
            params=task.get("params", {})
        )
        logger.info(f"Pre-analysis: {pre_analysis[:150]}...")

        # Task execution
        logger.info(f"Executing task: {name}")
        start = time.time()
        try:
            result = agent.run(self.state)
            elapsed = time.time() - start
            logger.info(f"Task {name} completed in {elapsed:.2f}s")
            self._ingest_result(phase, result)
            self._log_task_result(phase, name, result)
        except Exception as e:
            logger.error(f"Error in {name}: {e}", exc_info=True)
            result = {"error": str(e)}

        # Post-task AI analysis
        logger.info(f"Requesting post-analysis for {name}")
        post_analysis = self.ai.analyze_after_task(
            agent_name=name,
            phase=phase.name,
            state=self.state,
            result=result if result else {}
        )
        logger.info(f"Post-analysis: {post_analysis[:150]}...")
        return result

    def _enqueue_dynamic(self, agent_name: str, params: dict):
        """Add a new task to the dynamic queue (will be executed in the same phase or next)."""
        # Map agent name to actual agent instance
        agent_instance = self.agents.get(agent_name)
        if not agent_instance:
            logger.warning(f"Unknown agent '{agent_name}' – cannot enqueue")
            return
        # Determine phase based on agent (you may refine this)
        phase = self._guess_phase_for_agent(agent_name)
        task = {
            "agent": agent_instance,
            "name": agent_name,
            "phase": phase,
            "params": params
        }
        self.dynamic_tasks.append(task)
        logger.info(f"Dynamically enqueued task: {agent_name} (phase {phase.name})")

    def _guess_phase_for_agent(self, agent_name: str) -> AttackPhase:
        mapping = {
            "recon": AttackPhase.DISCOVERY,
            "cve": AttackPhase.CVE_CHECK,
            "auth": AttackPhase.AUTH_ATTACK,
            "exploit": AttackPhase.EXPLOITATION,
            "traffic": AttackPhase.DISCOVERY,
            "wp_enum": AttackPhase.EXPLOITATION,
            "report": AttackPhase.REPORT   # if you have a REPORT phase
        }
        return mapping.get(agent_name, AttackPhase.EXPLOITATION)

    def run(self):
        """Main orchestration loop with dynamic planning after each phase."""
        logger.info(f"Starting test on {self.state.target} ({self.state.ip})")
        phases = [AttackPhase.DISCOVERY, AttackPhase.CVE_CHECK, AttackPhase.AUTH_ATTACK, AttackPhase.EXPLOITATION]

        # Combine static tasks (from parent) and dynamic ones
        all_tasks = self.tasks[:]   # static tasks
        # Execute phase by phase, but also include dynamic tasks that belong to the current phase
        for phase in phases:
            logger.info(f"Starting phase {phase.value}...")
            # Collect tasks: static tasks for this phase + dynamic tasks for this phase
            phase_tasks = [t for t in all_tasks if t["phase"] == phase]
            # Add dynamic tasks that match this phase
            dynamic_here = [t for t in self.dynamic_tasks if t["phase"] == phase]
            phase_tasks.extend(dynamic_here)
            # Remove those dynamic tasks from the global list so they aren't repeated
            self.dynamic_tasks = [t for t in self.dynamic_tasks if t not in dynamic_here]

            if not phase_tasks:
                logger.info(f"No tasks for phase {phase.value}, skipping.")
                continue

            # Run tasks in parallel (max workers = number of tasks)
            with concurrent.futures.ThreadPoolExecutor(max_workers=len(phase_tasks)) as executor:
                futures = {executor.submit(self._run_task, task): task for task in phase_tasks}
                for future in concurrent.futures.as_completed(futures):
                    task = futures[future]
                    try:
                        future.result()
                    except Exception as e:
                        logger.error(f"Task {task['name']} raised exception: {e}")

            # After the phase, ask the AI for next actions
            last_result = {}
            if phase_tasks:
                # Use result of the last task in this phase (or aggregate)
                last_task = phase_tasks[-1]
                if hasattr(last_task.get("agent"), "last_result"):
                    last_result = last_task["agent"].last_result
                else:
                    # Fallback: try to get result from state or from task's stored result
                    pass
            suggestions = self.ai.plan_next_actions(self.state, phase.name, last_result)

            # Enqueue each suggestion as a new dynamic task
            for sugg in suggestions:
                agent_name = sugg.get("agent_name")
                params = sugg.get("params", {})
                if agent_name:
                    self._enqueue_dynamic(agent_name, params)

            # Small pause between phases
            time.sleep(1)

        logger.info("Test finished, generating report...")
        return self.state